#!/usr/bin/env node
/**
 * Process Cliopatria GeoJSON → browser-optimized data.
 * Strategy: deduplicate by name, keep largest-area snapshot per polity.
 * Adds Chinese translations + color overrides for major polities.
 */
const fs = require('fs');
const INPUT = 'cliopatria_polities_only.geojson';

// Chinese name translations
const ZH = {
  "Roman Republic": "羅馬共和國", "Roman Empire": "羅馬帝國",
  "Byzantine Empire": "拜占庭帝國", "Eastern Roman Empire": "東羅馬帝國",
  "Abbasid Caliphate": "阿拔斯王朝", "Umayyad Caliphate": "倭馬亞王朝",
  "Fatimid Caliphate": "法蒂瑪王朝", "Ayyubid Sultanate": "阿尤布王朝",
  "Mamluk Sultanate": "馬穆魯克蘇丹國",
  "Mongol Empire": "蒙古帝國", "Golden Horde": "金帳汗國",
  "Chagatai Khanate": "察合台汗國", "Ilkhanate": "伊兒汗國",
  "Ottoman Empire": "鄂圖曼帝國",
  "Holy Roman Empire": "神聖羅馬帝國",
  "Kingdom of England": "英格蘭王國", "Kingdom of France": "法蘭西王國",
  "Spanish Empire": "西班牙帝國", "Kingdom of Spain": "西班牙王國",
  "Portuguese Empire": "葡萄牙帝國", "Kingdom of Portugal": "葡萄牙王國",
  "British Empire": "大英帝國", "British Colonial Empire": "大英殖民帝國",
  "Kingdom of Great Britain": "大不列顛王國",
  "(British Empire)": "大英帝國",
  "United States of America": "美利堅合眾國",
  "Soviet Union": "蘇維埃社會主義共和國聯盟",
  "Russian Empire": "俄羅斯帝國", "Russian Federation": "俄羅斯聯邦",
  "(Russian Federation)": "俄羅斯聯邦",
  "France (Kingdom)": "法蘭西王國",
  "(French Consulate)": "法蘭西執政府", "French Consulate": "法蘭西執政府",
  "(French Fifth Republic)": "法蘭西第五共和國", "French Fifth Republic": "法蘭西第五共和國",
  "German Empire": "德意志帝國",
  "(Holy Roman Empire)": "神聖羅馬帝國",
  "(Kingdom of France)": "法蘭西王國",
  "(Kingdom of England)": "英格蘭王國",
  "Kingdom of Prussia": "普魯士王國",
  "Habsburg Monarchy": "哈布斯堡君主國", "(Habsburg Monarchy)": "哈布斯堡君主國",
  "Inca Empire": "印加帝國", "Aztec Empire": "阿茲特克帝國",
  "Mayan City-States": "馬雅城邦", "Later Mayan City-States": "後期馬雅城邦",
  "Olmec Civilization": "奧爾梅克文明",
  "Mughal Empire": "莫臥兒帝國", "(Delhi Sultanate)": "德里蘇丹國",
  "Gupta Empire": "笈多帝國", "Maurya Empire": "孔雀帝國",
  "Chola Empire": "朱羅帝國", "Vijayanagara Empire": "毗奢耶那伽羅帝國",
  "Maratha Empire": "馬拉塔帝國",
  "Safavid Empire": "薩法維帝國", "Qajar Dynasty": "卡扎爾王朝",
  "Parthian Empire": "帕提亞帝國", "Sasanian Empire": "薩珊帝國",
  "Great Seljuk Empire": "大塞爾柱帝國", "Seljuk Dynasty": "塞爾柱王朝",
  "Sultanate of Rum": "羅姆蘇丹國",
  "Timurid Empire": "帖木兒帝國",
  "Khwarezmid Dynasty": "花剌子模王朝",
  "Mali Empire": "馬里帝國", "Songhai Empire": "桑海帝國",
  "Ghana Empire": "加納帝國", "Ethiopian Empire": "衣索比亞帝國",
  "Kingdom of Kush": "庫什王國",
  "Achaemenid Empire": "阿契美尼德帝國",
  "Seleucid Empire": "塞琉古帝國",
  "Ptolemaic Kingdom": "托勒密王國",
  "Carthage": "迦太基",
  "Visigothic Kingdom": "西哥德王國",
  "Ostrogothic Kingdom": "東哥德王國",
  "Vandal Kingdom": "汪達爾王國",
  "Kingdom of the Franks": "法蘭克王國",
  "Merovingian Empire": "梅洛溫帝國",
  "(Merovingian Empire)": "梅洛溫帝國",
  "Carolingian Empire": "卡洛林帝國",
  "Kingdom of Scotland": "蘇格蘭王國",
  "Kingdom of Hungary": "匈牙利王國",
  "Kingdom of Poland": "波蘭王國", "(Kingdom of Poland)": "波蘭王國",
  "Kievan Rus'": "基輔羅斯",
  "Grand Duchy of Moscow": "莫斯科大公國",
  "Grand Principality of Moscow": "莫斯科大公國",
  "Novgorod Republic": "諾夫哥羅德共和國",
  "Kingdom of Norway": "挪威王國",
  "Kingdom of Sweden": "瑞典王國",
  "Denmark-Norway": "丹麥-挪威",
  "(Kalmar Union)": "卡爾馬聯盟", "Kalmar Union": "卡爾馬聯盟",
  "Swedish Empire": "瑞典帝國",
  "Dutch Republic": "荷蘭共和國",
  "Netherlands": "荷蘭", "(Netherlands)": "荷蘭",
  "Dutch East Indies": "荷屬東印度",
  "Kingdom of Italy": "義大利王國", "Republic of Italy": "義大利共和國",
  "Papal States": "教宗國",
  "Republic of Genoa": "熱那亞共和國",
  "Republic of Venice": "威尼斯共和國",
  "Kingdom of Two Sicilies": "兩西西里王國",
  "Belgium": "比利時", "Kingdom of Belgium": "比利時王國",
  "Luxembourg": "盧森堡",
  "Swiss Confederation": "瑞士聯邦",
  "Principality of Liechtenstein": "列支敦士登",
  "Republic of San Marino": "聖馬利諾共和國",
  "Kingdom of Serbia": "塞爾維亞王國",
  "Kingdom of Romania": "羅馬尼亞王國", "Romania": "羅馬尼亞",
  "Kingdom of Bulgaria": "保加利亞王國",
  "Kingdom of Greece": "希臘王國",
  "Albania": "阿爾巴尼亞",
  "Czechoslovakia": "捷克斯洛伐克",
  "Republic of Poland": "波蘭共和國",
  "Kingdom of Yugoslavia": "南斯拉夫王國",
  "SFR Yugoslavia": "南斯拉夫社會主義聯邦共和國",
  "Ottoman Empire": "鄂圖曼帝國",
  "Republic of Turkey": "土耳其共和國",
  "Syria": "敘利亞", "Lebanon": "黎巴嫩",
  "Iraq": "伊拉克", "Kingdom of Iraq": "伊拉克王國",
  "Transjordan": "外約旦",
  "State of Palestine": "巴勒斯坦國",
  "Kingdom of Saudi Arabia": "沙烏地阿拉伯王國",
  "Yemen": "葉門", "Republic of Yemen": "葉門共和國",
  "Oman": "阿曼", "Sultanate of Oman": "阿曼蘇丹國",
  "United Arab Emirates": "阿拉伯聯合大公國",
  "Kuwait": "科威特", "Qatar": "卡達", "Bahrain": "巴林",
  "Egypt": "埃及", "Arab Republic of Egypt": "阿拉伯埃及共和國",
  "Libya": "利比亞", "Libyan Arab Republic": "利比亞阿拉伯共和國",
  "Tunisia": "突尼西亞", "Algeria": "阿爾及利亞",
  "People's Democratic Republic of Algeria": "阿爾及利亞民主人民共和國",
  "Morocco": "摩洛哥",
  "Sudan": "蘇丹", "Republic of Sudan": "蘇丹共和國",
  "South Sudan": "南蘇丹",
  "Ethiopia": "衣索比亞", "Federal Democratic Republic of Ethiopia": "衣索比亞聯邦民主共和國",
  "Somalia": "索馬利亞", "Federal Republic of Somalia": "索馬利亞聯邦共和國",
  "Kenya": "肯亞", "Republic of Kenya": "肯亞共和國",
  "Tanzania": "坦尚尼亞",
  "Uganda": "烏干達", "Republic of Uganda": "烏干達共和國",
  "Rwanda": "盧安達", "Republic of Rwanda": "盧安達共和國",
  "Burundi": "蒲隆地", "Republic of Burundi": "蒲隆地共和國",
  "Democratic Republic of the Congo": "剛果民主共和國",
  "Republic of the Congo": "剛果共和國",
  "Gabon": "加彭", "Republic of Gabon": "加彭共和國",
  "Equatorial Guinea": "赤道幾內亞",
  "Cameroon": "喀麥隆", "Republic of Cameroon": "喀麥隆共和國",
  "Central African Republic": "中非共和國",
  "Chad": "乍得", "Republic of Chad": "乍得共和國",
  "Niger": "尼日", "Republic of the Niger": "尼日共和國",
  "Nigeria": "奈及利亞", "Federal Republic of Nigeria": "奈及利亞聯邦共和國",
  "Benin": "貝南", "Republic of Benin": "貝南共和國",
  "Togo": "多哥", "Republic of Togo": "多哥共和國",
  "Ghana": "迦納",
  "Ivory Coast": "象牙海岸", "Republic of Côte d'Ivoire": "象牙海岸共和國",
  "Liberia": "賴比瑞亞", "Republic of Liberia": "賴比瑞亞共和國",
  "Sierra Leone": "子子山", "Republic of Sierra Leone": "子子山共和國",
  "Guinea": "幾內亞", "Republic of Guinea": "幾內亞共和國",
  "Guinea-Bissau": "幾內亞比索", "Republic of Guinea-Bissau": "幾內亞比索共和國",
  "Gambia": "甘比亞", "Republic of The Gambia": "甘比亞共和國",
  "Senegal": "塞內加爾", "Republic of Senegal": "塞內加爾共和國",
  "Mali": "馬利", "Mali Federation": "馬利聯邦",
  "Mauritania": "茅利塔尼亞", "Mauritania": "茅利塔尼亞",
  "Burkina Faso": "布吉納法索",
  "Madagascar": "馬達加斯加",
  "Mauritius": "模里西斯",
  "Republic of South Africa": "南非共和國", "South Africa": "南非",
  "Namibia": "納米比亞", "Republic of Botswana": "波札那共和國",
  "Zimbabwe": "辛巴威", "Republic of Zimbabwe": "辛巴威共和國",
  "Zambia": "尚比亞",
  "Mozambique": "莫三比克",
  "Angola": "安哥拉", "People's Republic of Angola": "安哥拉人民共和國",
  "Malawi": "馬拉威",
  "Eswatini": "史瓦帝尼",
  "Lesotho": "賴索托",
  "Comoros": "葛摩",
  "Seychelles": "塞席爾",
  "Cape Verde": "維德角",
  "São Tomé and Príncipe": "聖多美和普林西比",
  "Timor-Leste": "東帝汶",
  "Brunei": "汶萊", "Sultanate of Brunei": "汶萊蘇丹國",
  "Singapore": "新加坡", "Republic of Singapore": "新加坡共和國",
  "Malaysia": "馬來西亞",
  "Indonesia": "印尼", "Republic of Indonesia": "印尼共和國",
  "Philippines": "菲律賓", "Republic of the Philippines": "菲律賓共和國",
  "Vietnam": "越南", "Socialist Republic of Vietnam": "越南社會主義共和國",
  "Laos": "寮國", "Communist Laos": "寮國",
  "Cambodia": "柬埔寨", "Kingdom of Cambodia": "柬埔寨王國",
  "Thailand": "泰國", "Kingdom of Thailand": "泰國王國",
  "Myanmar": "緬甸", "Union of Myanmar": "緬甸聯邦",
  "Bangladesh": "孟加拉", "People's Republic of Bangladesh": "孟加拉人民共和國",
  "Sri Lanka": "斯里蘭卡",
  "Nepal": "尼泊爾",
  "Bhutan": "不丹", "Kingdom of Bhutan": "不丹王國",
  "Maldives": "馬爾地夫",
  "Pakistan": "巴基斯坦", "Islamic Republic of Pakistan": "巴基斯坦伊斯蘭共和國",
  "India": "印度", "Republic of India": "印度共和國",
  "Afghanistan": "阿富汗",
  "Iran": "伊朗", "Islamic Republic of Iran": "伊朗伊斯蘭共和國",
  "Mongolia": "蒙古",
  "North Korea": "北韓", "Democratic People's Republic of Korea": "朝鮮民主主義人民共和國",
  "South Korea": "南韓", "Republic of Korea": "大韓民國",
  "Japan": "日本",
  "Taiwan": "臺灣", "Republic of China": "中華民國",
  "China": "中國", "People's Republic of China": "中華人民共和國",
  "Hong Kong": "香港", "Macau": "澳門",
  "Mexico": "墨西哥", "United Mexican States": "墨西哥合眾國",
  "Guatemala": "瓜地馬拉", "Republic of Guatemala": "瓜地馬拉共和國",
  "Belize": "貝里斯",
  "Honduras": "宏都拉斯", "Republic of Honduras": "宏都拉斯共和國",
  "El Salvador": "薩爾瓦多", "Republic of El Salvador": "薩爾瓦多共和國",
  "Nicaragua": "尼加拉瓜", "Republic of Nicaragua": "尼加拉瓜共和國",
  "Costa Rica": "哥斯大黎加", "Republic of Costa Rica": "哥斯大黎加共和國",
  "Panama": "巴拿馬", "Republic of Panama": "巴拿馬共和國",
  "Cuba": "古巴", "Communist Cuba": "古巴",
  "Jamaica": "牙買加",
  "Haiti": "海地", "Republic of Haiti": "海地共和國",
  "Dominican Republic": "多明尼加共和國",
  "Trinidad and Tobago": "千里達及多巴哥", "Republic of Trinidad and Tobago": "千里達及多巴哥共和國",
  "Barbados": "巴貝多",
  "Bahamas": "巴哈馬", "Commonwealth of The Bahamas": "巴哈馬聯邦",
  "Antigua and Barbuda": "安地卡及巴布達",
  "Saint Kitts": "聖克里斯多福",
  "Saint Vincent": "聖文森",
  "Dominica": "多明尼克",
  "Saint Lucia": "聖露西亞",
  "Grenada": "格瑞那達",
  "Suriname": "蘇利南",
  "Guyana": "蓋亞那",
  "Belize": "貝里斯",
  "Canada": "加拿大",
  "Australia": "澳大利亞", "Commonwealth of Australia": "澳大利亞聯邦",
  "New Zealand": "紐西蘭",
  "Papua New Guinea": "巴布亞紐幾內亞",
  "Fiji": "斐濟", "Republic of Fiji": "斐濟共和國",
  "Solomon Islands": "索羅門群島",
  "Vanuatu": "萬那杜",
  "Samoa": "薩摩亞",
  "Tonga": "東加",
  "Iceland": "冰島", "Republic of Iceland": "冰島共和國",
  "Ireland": "愛爾蘭",
  "Finland": "芬蘭", "Republic of Finland": "芬蘭共和國",
  "Estonia": "愛沙尼亞", "Republic of Estonia": "愛沙尼亞共和國",
  "Latvia": "拉脫維亞", "Republic of Latvia": "拉脫維亞共和國",
  "Lithuania": "立陶宛", "Republic of Lithuania": "立陶宛共和國",
  "Belarus": "白俄羅斯", "Republic of Belarus": "白俄羅斯共和國",
  "Ukraine": "烏克蘭",
  "Moldova": "摩爾多瓦",
  "Georgia": "喬治亞",
  "Armenia": "亞美尼亞", "Republic of Armenia": "亞美尼亞共和國",
  "Azerbaijan": "亞塞拜然", "Republic of Azerbaijan": "亞塞拜然共和國",
  "Kazakhstan": "哈薩克", "Republic of Kazakhstan": "哈薩克共和國",
  "Uzbekistan": "烏茲別克", "Republic of Uzbekistan": "烏茲別克共和國",
  "Turkmenistan": "土庫曼",
  "Kyrgyzstan": "吉爾吉斯",
  "Tajikistan": "塔吉克",
  "Bulgaria": "保加利亞",
  "Hungary": "匈牙利",
  "Czech Republic": "捷克",
  "Slovakia": "斯洛伐克",
  "Slovenia": "斯洛維尼亞",
  "Croatia": "克羅埃西亞",
  "Bosnia and Herzegovina": "波士尼亞與赫塞哥維納",
  "North Macedonia": "北馬其頓",
  "Montenegro": "蒙特內哥羅",
  "Serbia": "塞爾維亞",
  "Kosovo": "科索沃",
  "Luxembourg": "盧森堡",
  "Cyprus": "賽普勒斯",
  "Malta": "馬爾他",
  "Andorra": "安道爾", "Principality of Andorra": "安道爾公國",
  "Monaco": "摩納哥", "Principality of Monaco": "摩納哥公國",
  "San Marino": "聖馬利諾",
  "Vatican City": "梵蒂岡",
  "Holy See": "聖座",
  "Brunei": "汶萊",
  "Bolivia": "玻利維亞",
  "Chile": "智利", "Republic of Chile": "智利共和國",
  "Argentina": "阿根廷", "Argentine Republic": "阿根廷共和國",
  "Paraguay": "巴拉圭",
  "Uruguay": "烏拉圭", "Oriental Republic of Uruguay": "烏拉圭東岸共和國",
  "Peru": "秘魯", "Republic of Peru": "秘魯共和國",
  "Ecuador": "厄瓜多", "Republic of Ecuador": "厄瓜多共和國",
  "Colombia": "哥倫比亞", "Republic of Colombia": "哥倫比亞共和國",
  "Venezuela": "委內瑞拉",
  "Brazil": "巴西", "Republic of Brazil": "巴西共和國",
  "Guyana": "蓋亞那",
  "Suriname": "蘇利南",
  "Korean Empire": "大韓帝國",
  "Joseon": "朝鮮王朝",
  "Goryeo": "高麗",
  "Silla": "新羅",
  "Baekje": "百濟",
  "Goguryeo": "高句麗",
  "Jinhan": "辰韓",
  "Byeonhan": "弁韓",
  "Mahan": "馬韓",
  "Heian Japan": "平安時代",
  "Kamakura Shogunate": "鐮倉幕府",
  "Ashikaga Shogunate": "室町幕府",
  "Tokugawa Shogunate": "德川幕府",
  "Warring States Japan": "日本戰國",
  "Shunten Dynasty": "舜天王朝",
  "Ryukyu Kingdom": "琉球王國",
  "Khmer Empire": "高棉帝國",
  "Champa": "占婆",
  "Srivijaya": "三佛齊",
  "Majapahit": "滿者伯夷",
  "Ayutthaya Kingdom": "阿瑜陀耶王國",
  "Lan Xang": "瀾滄王國",
  "Pagan Kingdom": "蒲甘王國",
  "Haripuñjaya": "哈里奔猜王國",
  "Sunda Kingdom": "巽他王國",
  "Galuh Kingdom": "古爾王国",
  "Kediri Kingdom": "迪爾吉王國",
  "Mataram Kingdom": "馬打蘭王國",
  "Early Balinese Kingdoms": "早期巴厘王國",
  "Lavo Kingdom": "羅渦王國",
  "Tamna": "耽羅",
  "Kingdom of Polonnaruwa": "波隆納魯瓦王國",
  "Anurādhapura": "阿努拉德普勒王國",
  "Kadamba Empire": "達摩王朝",
  "Kamarupa Kingdom": "迦摩縷波王國",
  "Pala Empire": "波羅王朝",
  "Chandra Dynasty": "旃陀羅王朝",
  "Kumar Bhaskaravarman": "迦摩縷波王國",
  "Satavahana Dynasty": "百乘王朝",
  "Vakataka王朝": "伐卡塔卡王朝",
  "Western Chalukya Empire": "西遮婁其帝國",
  "Eastern Ganga Kingdom": "東恒伽王國",
  "Kakatiya Dynasty": "卡卡提亞王朝",
  "Hoysala Empire": "曷薩拉帝國",
  "Yadava Dynasty": "亞達瓦王朝",
  "Chaulukya Dynasty": "朱羅俱吒王朝",
  "Paramara Dynasty": "帕拉馬拉王朝",
  "Chandela王朝": "旃陀羅王朝",
  "Lohara Dynasty": "洛哈拉王朝",
  "Gurjara-Pratihara Dynasty": "瞿折羅-普拉蒂哈拉王朝",
  "Kalabhra Dynasty": "迦拉布拉王朝",
  "Late Pallava Empire": "帕拉瓦帝國",
  "Early Cholas": "早期朱羅", "Early Cheras": "早期哲羅",
  "Early Pandyas": "早期潘地亞",
  "Gondar": "貢德爾",
  "Kingdom of Aksum": "阿克蘇姆王國",
  "Zagwe dynasty": "札格維王朝",
  "Ethiopian Empire": "衣索比亞帝國",
  "Adal Sultanate": "阿達爾蘇丹國",
  "Makuria": "穆庫拉王國",
  "Alodia": "阿洛迪亞王國",
  "Funj Sultanate": "豐吉蘇丹國",
  "Bornu Empire": "博爾努帝國",
  "Empire of Kanem": "卡內姆帝國",
  "Songhai Empire": "桑海帝國",
  "Mali Empire": "馬里帝國",
  "Ashanti Empire": "阿散蒂帝國",
  "Kingdom of Kongo": "剛果王國",
  "Lunda Empire": "隆達王國",
  "Oyo Empire": "奧約帝國",
  "Kanem–Bornu Empire": "卡內姆-博爾努帝國",
  "Wadai Empire": "瓦達伊帝國",
  "Sultanate of Darfur": "達爾富爾蘇丹國",
  "Kingdom of Luba": "盧巴王國",
  "Sultanate of Sulu": "蘇祿蘇丹國",
  "Sultanate of Maguindanao": "馬京達瑙蘇丹國",
  "Rajahnate of Cebu": "宿霧王國",
  "Tondo": "湯都",
  "Namayan": "納馬延",
  "Sultanate of Malacca": "馬六甲蘇丹國",
  "Sultanate of Aceh": "亞齊蘇丹國",
  "Sultanate of Demak": "淡目蘇丹國",
  "Sultanate of Mataram": "馬打蘭蘇丹國",
  "Sultanate of Banten": "萬丹蘇丹國",
  "Sultanate of Cirebon": "井里汶蘇丹國",
  "Sultanate of Palembang": "巨港蘇丹國",
  "Sultanate of Jambi": "占碑蘇丹國",
  "Sultanate of Banjar": "班賈爾蘇丹國",
  "Sultanate of Kutai Kartanegara": "古泰卡爾塔內加拉蘇丹國",
  "Sultanate of Sambas": "三巴斯蘇丹國",
  "Sultanate of Sukadana": "蘇卡達納蘇丹國",
  "Sultanate of Bima": "比馬蘇丹國",
  "Sultanate of Bone": "博內蘇丹國",
  "Sultanate of Selangor": "雪蘭莪蘇丹國",
  "Sultanate of Perak": "霹靂蘇丹國",
  "Sultanate of Kedah": "吉打蘇丹國",
  "Sultanate of Brunei": "汶萊蘇丹國",
  "Sultanate of Terengganu": "登嘉樓蘇丹國",
  "Sultanate of Johor": "柔佛蘇丹國",
  "Kelantan": "吉蘭丹",
  "Negeri Sembilan": "森美蘭",
  "Sultan of Yogyakarta": "日惹蘇丹國",
  "Surakarta Sunanate": "梭羅王國",
  "Lê王朝": "黎朝",
  "Đại Việt": "大越",
  "Tây Sơn王朝": "西山朝",
  "Ngô王朝": "吳朝",
  "Mạc王朝": "莫朝",
  "Trịnh Lords": "鄭主",
  "Nguyễn Lords": "阮主",
  "Nguyễn王朝": "阮朝",
  "Confederation of Vietnam": "越南聯邦",
  "Kingdom of Vietnam": "越南王國",
  "Empire of Vietnam": "越南帝國",
  "State of Vietnam": "越南國",
  "Haudenosaunee": "易洛魁聯盟",
  "Puebloans - Chaco Regional System": "普韋布洛人-查科區域系統",
  "Puebloans - Aztec Regional System": "普韋布洛人-阿茲特克區域系統",
  "Classic Veracruz Culture": "古典維拉克魯斯文化",
  "Chimor": "奇穆王國",
  "Toltec": "托爾特克",
  "Tarascan State": "塔拉斯科王國",
  "Kievan Rus'": "基輔羅斯",
  "Principality of Ryazan": "梁贊公國",
  "Principality of Rostov-Suzdal": "羅斯托夫-蘇茲達爾公國",
  "Principality of Chernigov": "切爾尼戈夫公國",
  "Principality of Pereyaslavl": "佩列亞斯拉夫爾公國",
  "Principality of Galicia-Volhynia": "加利奇-沃里尼亞公國",
  "Halych-Volhynia occupation": "加利奇-沃里尼亞",
  "Principality of Antioch": "安條克公國",
  "County of Tripoli": "的黎波里伯國",
  "Principality of Orange": "奧朗日公國",
  "Principality of Wallachia": "瓦拉幾亞公國",
  "Principality of Moldavia": "摩爾達維亞公國",
  "Principality of Transylvania": "外西凡尼亞公國",
  "Principality of Abkhazia": "阿布哈茲公國",
  "Principality of Mingrelia": "明格列利亞公國",
  "Kingdom of Imereti": "伊梅列季亞王國",
  "Kingdom of Kakheti": "卡赫季亞王國",
  "Kingdom of Kartli-Kakheti": "卡爾特利-卡赫季亞王國",
  "Duchy of Bavaria": "巴伐利亞公國",
  "Duchy of Saxony": "薩克森公國",
  "Duchy of Swabia": "士瓦本公國",
  "Duchy of Franconia": "法蘭肯公國",
  "Duchy of Burgundy": "勃艮第公國",
  "Duchy of Normandy": "諾曼第公國",
  "Duchy of Brittany": "布列塔尼公國",
  "County of Champagne": "香檳伯國",
  "County of Anjou": "安茹伯國",
  "County of Maine": "曼恩伯國",
  "County of Vexin": "韋克辛伯國",
  "County of Urgell": "烏赫爾伯國",
  "County of Tripoli": "的黎波里伯國",
  "County of Flanders": "法蘭德斯伯國",
  "Republic of Amalfi": "阿馬爾菲共和國",
  "Republic of Ragusa": "拉古薩共和國",
  "Principality of Salerno": "薩萊諾親王國",
  "Kingdom of Sicily": "西西里王國",
  "Kingdom of Cyprus": "塞普勒斯王國",
  "Sardinian Kingdom": "撒丁王國",
  "Giudicato of Gallura": "加盧拉",
  "Giudicato of Logudoro": "洛古多羅",
  "Giudicato of Arborea": "阿爾博雷亞",
  "Giudicato of Cagliari": "卡利亞里",
  "Kingdom of the Two Sicilies": "兩西西里王國",
  "Grand Duchy of Tuscany": "托斯卡納大公國",
  "Kingdom of Sardinia": "薩丁尼亞王國",
  "Emirate of Sicily": "西西里埃米爾國",
  "Old Kingdom of Norway": "挪威王國",
  "Viking settlements": "維京人定居點",
  "Norse Greenland": "諾斯格陵蘭",
  "Icelandic Commonwealth": "冰島聯邦",
  "Kingdom of Alba": "阿爾巴王國",
  "Kingdom of the Isles": "群島王國",
  "Kingdom of Mann": "曼島王國",
  "Kingdom of Gwynedd": "格溫內斯王國",
  "Kingdom of Powys": "波伊斯王國",
  "Kingdom of Gwent": "格溫特王國",
  "Kingdom of Morgannwg": "摩根威格王國",
  "Kingdom of Brycheiniog": "布雷切尼奧格王國",
  "Brythons": "布立吞人",
  "(Brythonic Kingdoms)": "布立吞諸王國",
  "Scandinavian minor kingdoms": "斯堪的納維亞小王國",
  "Saxon Kingdom": "薩克森王國",
  "Kingdom of Sussex": "蘇塞克斯王國",
  "Kingdom of Kent": "肯特王國",
  "Kingdom of East Anglia": "東盎格利亞王國",
  "Kingdom of Essex": "埃塞克斯王國",
  "Kingdom of Wessex": "威塞克斯王國",
  "Kingdom of Mercia": "麥西亞王國",
  "Kingdom of Northumbria": "諾森布里亞王國",
  "Heptarchy": "七王國",
  "Danelaw": "丹麥法區",
  "Kingdom of England": "英格蘭王國",
  "Angevin Empire": "安茹帝國",
  "Principality of Wales": "威爾斯親王國",
  "Lordship of Ireland": "愛爾蘭領地",
  "Crown of Castile": "卡斯提爾王冠",
  "Crown of Aragon": "亞拉岡王冠",
  "Kingdom of Navarre": "納瓦拉王國",
  "Al-Andalus": "安達盧斯",
  "Emirate of Córdoba": "科爾多瓦埃米爾國",
  "Caliphate of Córdoba": "科爾多瓦哈里發國",
  "Kingdom of León": "雷昂王國",
  "County of Portugal": "葡萄牙伯國",
  "Kingdom of Portugal": "葡萄牙王國",
  "Kingdom of Galicia": "加利西亞王國",
  "Basque Country": "巴斯克",
  "Kingdom of Castile": "卡斯提爾王國",
  "Kingdom of Aragon": "亞拉岡王國",
  "Crown of Castile": "卡斯提爾王冠",
  "Crown of Aragon": "亞拉岡王冠",
  "Kingdom of Hungary": "匈牙利王國",
  "Kingdom of Bohemia": "波希米亞王國",
  "Kingdom of Croatia": "克羅埃西亞王國",
  "Kingdom of Bosnia": "波士尼亞王國",
  "Kingdom of Serbia": "塞爾維亞王國",
  "Kingdom of Bulgaria": "保加利亞王國",
  "First Bulgarian Empire": "第一保加利亞帝國",
  "Second Bulgarian Empire": "第二保加利亞帝國",
  "Kingdom of Albania": "阿爾巴尼亞王國",
  "Despotate of Epirus": "伊庇魯斯專制公國",
  "Principality of Achaea": "阿哈伊亞親王國",
  "Duchy of Athens": "雅典公國",
  "Kingdom of Thessalonica": "帖撒羅尼迦王國",
  "Empire of Nicaea": "尼西亞帝國",
  "Empire of Trebizond": "特拉布宗帝國",
  "Despotate of Morea": "摩里亞專制公國",
  "Karamanids": "卡拉曼侯國",
  "Dulkadirids": "杜勒卡迪爾侯國",
  "Ramazanids": "拉馬贊侯國",
  "Aq Qoyunlu": "白羊王朝",
  "Qara Qoyunlu": "黑羊王朝",
  "Talpur dynasty": "塔爾普爾王朝",
  "Barakzai dynasty": "巴拉克扎伊王朝",
  "Hotaki dynasty": "霍塔克王朝",
  "Durrani Empire": "杜蘭尼帝國",
  "Safavid dynasty": "薩法維王朝",
  "Afsharid dynasty": "阿夫沙爾王朝",
  "Zand dynasty": "桑德王朝",
  "Nader Shah": "納迪爾沙",
  "White Huns": "嚈噠",
  "Hephthalite Empire": "嚈噠帝國",
  "Hunnic Empire": "匈人帝國",
  "Xiongnu": "匈奴",
  "Rouran Khaganate": "柔然汗國",
  "Göktürk Khaganate": "突厥汗國",
  "Western Turkic Khaganate": "西突厥",
  "Eastern Turkic Khaganate": "東突厥",
  "Uyghur Khaganate": "回鶻汗國",
  "Yenisei Kyrgyz": "黠戛斯",
  "Kimek-Kipchak confederation": "基馬克-欽察聯盟",
  "Cuman-Kipchak Confederation": "欽察-庫曼聯盟",
  "Oghuz Turks": "烏古斯突厥",
  "Karakhanids": "喀喇汗國",
  "Ghaznavid Empire": "伽色尼王朝",
  "Khorasan": "呼羅珊",
  "Great Seljuk Empire": "大塞爾柱帝國",
  "Khwarazmian Empire": "花剌子模帝國",
  "Qara Khitai": "西遼",
  "Khwarazmid Dynasty": "花剌子模王朝",
  "Timurid Empire": "帖木兒帝國",
  "Mughal Empire": "莫臥兒帝國",
  "Sur Empire": "蘇爾王朝",
  "Suri dynasty": "蘇爾王朝",
  "Sultanate of Delhi": "德里蘇丹國",
  "Bahmani Sultanate": "巴赫曼尼蘇丹國",
  "Deccan Sultanates": "德干蘇丹國",
  "Bijapur Sultanate": "比賈布爾蘇丹國",
  "Golconda Sultanate": "戈爾孔達蘇丹國",
  "Ahmadnagar Sultanate": "艾哈邁德納加爾蘇丹國",
  "Bidar Sultanate": "比達爾蘇丹國",
  "Berar Sultanate": "貝拉爾蘇丹國",
  "Sultanate of Bengal": "孟加拉蘇丹國",
  "Sultanate of Gujarat": "古吉拉特蘇丹國",
  "Sultanate of Malwa": "馬爾瓦蘇丹國",
  "Sultanate of Kashmir": "喀什米爾蘇丹國",
  "Sind": "信德",
  "Punjab": "旁遮普",
  "Awadh": "奧德",
  "Hyderabad": "海德拉巴",
  "Mysore": "邁索爾",
  "Travancore": "特拉凡科爾",
  "Cochin": "科欽",
  "Kozhikode": "科澤科德",
  "Kingdom of Mysore": "邁索爾王國",
  "Kingdom of Travancore": "特拉凡科爾王國",
  "Kingdom of Cochin": "科欽王國",
  "French India": "法屬印度",
  "Portuguese India": "葡屬印度",
  "British India": "英屬印度",
  "Dominion of India": "印度自治領",
  "Dominion of Pakistan": "巴基斯坦自治領",
  "Union of Soviet Socialist Republics": "蘇維埃社會主義共和國聯盟",
  "Confederate States of America": "美利堅聯盟國",
  "French Indochina": "法屬印度支那",
  "Dutch East Indies": "荷屬東印度",
  "British Malaya": "英屬馬來亞",
  "British Burma": "英屬緬甸",
  "French West Africa": "法屬西非",
  "French Equatorial Africa": "法屬赤道非洲",
  "Italian East Africa": "意屬東非",
  "Italian Libya": "意屬利比亞",
  "Italian Eritrea": "意屬厄利垂亞",
  "Italian Somaliland": "義屬索馬利蘭",
  "Japanese Empire": "大日本帝國",
  "Empire of Japan": "大日本帝國",
  "Korea under Japanese rule": "日治朝鮮",
  "Taiwan under Japanese rule": "日治臺灣",
  "Manchukuo": "滿洲國",
  "Republic of China (1912–1949)": "中華民國",
  "Nanjing regime": "南京國民政府",
  "Wang Jingwei regime": "汪精衛國民政府",
  "People's Republic of China": "中華人民共和國",
  "Empire of Brazil": "巴西帝國",
  "United States of Brazil": "巴西合眾國",
  "Argentine Confederation": "阿根廷邦聯",
  "Argentine Republic": "阿根廷共和國",
  "United Provinces of Central America": "中美洲聯合省",
  "Federal Republic of Central America": "中美洲聯邦共和國",
  "Gran Colombia": "大哥倫比亞",
  "Republic of New Granada": "新格拉納達共和國",
  "United States of Colombia": "哥倫比亞合眾國",
  "Republic of Venezuela": "委內瑞拉共和國",
  "Bolivarian Republic of Venezuela": "委內瑞拉玻利瓦爾共和國",
  "Republic of Peru": "秘魯共和國",
  "Peruvian Republic": "秘魯共和國",
  "State of Peru": "秘魯國",
  "Republic of Bolivia": "玻利維亞共和國",
  "Plurinational State of Bolivia": "多民族玻利維亞國",
  "Republic of Chile": "智利共和國",
  "Republic of Paraguay": "巴拉圭共和國",
  "Oriental Republic of Uruguay": "烏拉圭東岸共和國",
  "Empire of Haiti": "海地帝國",
  "Republic of Haiti": "海地共和國",
  "Dominican Republic": "多明尼加共和國",
  "Spanish Empire": "西班牙帝國",
  "New Spain": "新西班牙",
  "Viceroyalty of Peru": "秘魯總督區",
  "Viceroyalty of New Granada": "新格拉納達總督區",
  "Viceroyalty of the Río de la Plata": "拉普拉塔總督區",
  "United Provinces of New Granada": "新格拉納達聯合省",
  "Gran Colombia": "大哥倫比亞",
  "Empire of Brazil": "巴西帝國",
  "Kingdom of Portugal": "葡萄牙王國",
  "State of Brazil": "巴西",
  "United Kingdom of Portugal": "葡萄牙聯合王國",
  "Portuguese Empire": "葡萄牙帝國",
  "Dutch Republic": "荷蘭共和國",
  "Batavian Republic": "巴達維亞共和國",
  "Kingdom of Holland": "荷蘭王國",
  "(Batavian Republic)": "巴達維亞共和國",
  "Cisalpine Republic": "阿爾卑斯共和國",
  "Transpadane Republic": "特蘭斯帕達共和國",
  "Cisrhenian Republic": "萊茵河內共和國",
  "Helvetic Republic": "赫爾維蒂共和國",
  "Parthenopean Republic": "帕爾泰諾佩共和國",
  "Roman Republic (18th century)": "羅馬共和國",
  "Ligurian Republic": "利古里亞共和國",
  "Ionian Islands under French rule": "法屬愛奧尼亞群島",
  "Kingdom of Italy (Napoleonic)": "義大利王國",
  "Kingdom of Naples": "那不勒斯王國",
  "Kingdom of Sicily": "西西里王國",
  "Grand Duchy of Hesse": "黑森大公國",
  "Grand Duchy of Baden": "巴登大公國",
  "Grand Duchy of Württemberg": "符騰堡大公國",
  "Grand Duchy of Oldenburg": "奧爾登堡大公國",
  "Grand Duchy of Mecklenburg-Schwerin": "梅克倫堡-什未林大公國",
  "Electorate of Hanover": "漢諾威選侯國",
  "Electorate of Saxony": "薩克森選侯國",
  "Electorate of Bavaria": "巴伐利亞選侯國",
  "Electorate of Brandenburg": "勃蘭登堡選侯國",
  "Electorate of Trier": "特里爾選侯國",
  "Electorate of Mainz": "美因茨選侯國",
  "Electorate of Cologne": "科隆選侯國",
  "Free Imperial Cities": "自由帝國城市",
  "Prince-Bishopric of Liège": "列日親王主教區",
  "Prince-Bishopric of Münster": "明斯特親王主教區",
  "Prince-Bishopric of Salzburg": "薩爾斯堡親王主教區",
  "Prince-Bishopric of Würzburg": "維爾茨堡親王主教區",
  "Prince-Bishopric of Bamberg": "班貝格親王主教區",
  "Prince-Bishopric of Worms": "沃爾姆斯親王主教區",
  "Prince-Bishopric of Strasbourg": "史特拉斯堡親王主教區",
  "Prince-Bishopric of Augsburg": "奧格斯堡親王主教區",
  "Prince-Bishopric of Eichstätt": "艾希施泰特親王主教區",
  "Prince-Bishopric of Regensburg": "雷根斯堡親王主教區",
  "Prince-Bishopric of Passau": "帕紹親王主教區",
  "Prince-Bishopric of Freising": "弗賴辛親王主教區",
  "Prince-Bishopric of Hildesheim": "希爾德斯海姆親王主教區",
  "Prince-Bishopric of Paderborn": "帕德博恩親王主教區",
  "Prince-Bishopric of Osnabrück": "奧斯納布呂克親王主教區",
  "Prince-Bishopric of Verden": "費爾登親王主教區",
  "Prince-Bishopric of Bremen": "不萊梅親王主教區",
  "Prince-Bishopric of Schwerin": "什未林親王主教區",
  "Prince-Bishopric of Ratzeburg": "拉策堡親王主教區",
  "Prince-Bishopric of Lübeck": "呂貝克親王主教區",
  "Prince-Bishopric of Cammin": "卡明親王主教區",
  "Prince-Bishopric of Kulm": "庫爾姆親王主教區",
  "Prince-Bishopric of Ermland": "埃爾姆蘭德親王主教區",
  "Prince-Bishopric of Olmütz": "奧爾米茨親王主教區",
  "Prince-Bishopric of Breslau": "布雷斯勞親王主教區",
  "Prince-Bishopric of Meißen": "邁森親王主教區",
  "Prince-Bishopric of Naumburg-Zeitz": "瑙姆堡-蔡茨親王主教區",
  "Prince-Bishopric of Merseburg": "梅澤堡親王主教區",
  "Prince-Bishopric of Halberstadt": "哈爾伯施塔特親王主教區",
  "Prince-Bishopric of Minden": "明登親王主教區",
  "Prince-Bishopric of Schwerin": "什未林親王主教區",
  "Prince-Bishopric of Ratzeburg": "拉策堡親王主教區",
  "Prince-Bishopric of Lübeck": "呂貝克親王主教區",
  "Prince-Bishopric of Cammin": "卡明親王主教區",
  "Prince-Bishopric of Kulm": "庫爾姆親王主教區",
  "Prince-Bishopric of Ermland": "埃爾姆蘭德親王主教區",
  "Prince-Bishopric of Olmütz": "奧爾米茨親王主教區",
  "Prince-Bishopric of Breslau": "布雷斯勞親王主教區",
  "Prince-Bishopric of Meißen": "邁森親王主教區",
  "Prince-Bishopric of Naumburg-Zeitz": "瑙姆堡-蔡茨親王主教區",
  "Prince-Bishopric of Merseburg": "梅澤堡親王主教區",
  "Prince-Bishopric of Halberstadt": "哈爾伯施塔特親王主教區",
  "Prince-Bishopric of Minden": "明登親王主教區",
  "Rashidun Caliphate": "正統哈里發國",
  "Abbasid Caliphate/Buyid Dynasty": "阿拔斯/布伊王朝",
  "Akkadian Empire": "阿卡德帝國",
  "Indus Valley Civilization": "印度河流域文明",
  "Middle Kingdom of Egypt": "古埃及中王國",
  "New Kingdom of Egypt": "古埃及新王國",
  "Hittites": "西臺帝國",
  "Assyria": "亞述帝國",
  "Neo-Assyrian Empire": "新亞述帝國",
  "Neo-Babylonian Empire": "新巴比倫帝國",
  "Median Kingdom": "米底王國",
  "Macedonian Empire": "馬其頓帝國", "(Macedonian Empire)": "馬其頓帝國",
  "Greco-Bactrian Kingdom": "希臘-巴克特里亞王國",
  "Kingdom of Pontus": "本都王國",
  "Kingdom of Armenia": "亞美尼亞王國",
  "Kushan Empire": "貴霜帝國",
  "Western Satraps": "西徐亞總督區",
  "Xianbei": "鮮卑",
  "Protectorate of the Western Regions": "西域都護府",
  "Cao Cao": "曹操", "Eastern Wu": "東吳", "Shu Han": "蜀漢", "Cao Wei": "曹魏",
  "Xin Dynasty": "新朝",
  "Kingdom of Numidia": "努米底亞王國",
  "Scythia": "西徐亞",
  "Yuezhi": "月氏",
  "(Mahajanapadas)": "十六雄國",
  "(Eighteen Kingdoms)": "十八諸侯",
  "Minyue": "閩越", "Nanyue": "南越", "Western Chu": "西楚",
  "Himyarite Kingdom": "希木葉爾王國",
  "Indo-Scythians": "印度-西徐亞",
  "Indo-Greeks": "印度-希臘",
  "Indo-Parthians": "印度-帕提亞",
  "Indo-Sasanian Empire": "印度-薩珊帝國",
  "Kidarites": "寄多羅",
  "Huns": "匈人",
  "Xionites": "匈尼特人",
  "Tuyuhun": "吐谷渾",
  "Vakataka Dynasty": "伐卡塔卡王朝",
  "Harsha's Empire": "戒日帝國",
  "Chalukya Dynasty": "遮婁其王朝",
  "Rashtrakuta Dynasty": "拉什特拉庫塔王朝",
  "Maitraka Dynasty": "邁特拉卡王朝",
  "Balhae": "渤海國",
  "Mahameghavahana Dynasty": "摩醯波羅王朝",
  "Shunga Empire": "巽伽王朝",
  "Kanva Dynasty": "甘瓦王朝",
  "Kingdom of Axum": "阿克蘇姆王國",
  "Nanda Empire": "難陀王朝",
  "Kingdom of Lysimachus": "利西馬科斯王國",
  "Chenla": "真臘", "(Chenla)": "真臘",
  "Gothia": "哥德王國",
  "Vandals": "汪達爾王國",
  "Ostrogoths": "東哥德王國",
  "(Kingdom of the Franks)": "法蘭克王國",
  "Kingdom of Germany": "德意志王國",
  "Eastern Wei": "東魏", "Western Wei": "西魏",
  "Northern Zhou": "北周", "Chen Dynasty": "陳朝",
  "Western Roman Empire": "西羅馬帝國",
  "Eastern Kushans": "東貴霜", "Western Kushans": "西貴霜",
  "Kannauj-Varman Dynasty": "坎諾吉-伐摩王朝",
  "Maukhari Dynasty": "穆克里王朝",
  "Western Göktürks": "西突厥", "Eastern Göktürks": "東突厥",
  "Gallic Empire": "高盧帝國",
  "Palmyrene Empire": "帕爾米拉帝國",
  "Cheng Han": "成漢",
  "Former Zhao": "前趙", "Former Yan": "前燕",
  "Later Zhao": "後趙", "Former Qin": "前秦",
  "Later Qin": "後秦", "Later Yan": "後燕",
  "Northern Wei": "北魏",
  "Turks": "突厥",
  "Türgesh": "突騎施",
  "Turk Shahis": "突厥沙希",
  "Old Great Bulgaria": "大保加利亞",
  "Avar Khaganate": "阿瓦爾汗國",
  "Burgundian Kingdom": "勃艮第王國",
  "Kingdom of Lombards": "倫巴底王國",
  "Crimean Khanate": "克里米亞汗國",
  "Khazaria": "可薩汗國",
  "Rus'": "羅斯",
  "Kingdom of Khotan": "于闐王國",
  "Southern Han": "南漢",
  "Former Shu": "前蜀", "Southern Chu": "楚",
  "Southern Wu": "南吳", "Liao Dynasty": "遼朝",
  "Later Tang": "後唐", "Later Jin": "後晉",
  "Later Shu": "後蜀", "Later Han": "後漢",
  "Southern Tang": "南唐", "Later Zhou": "後周",
  "Buyid Dynasty": "布伊王朝",
  "Hamdanid Emirates": "哈姆丹王朝",
  "Saffarid Dynasty": "薩法爾王朝",
  "Tulunids": "圖倫王朝",
  "Rustamid dynasty": "魯斯塔姆王朝",
  "Qarlugs": "葛邏祿",
  "Magyars": "馬扎爾人",
  "Kara-Khanids": "喀喇汗國",
  "East Franks": "東法蘭克王國",
  "West Franks": "西法蘭克王國",
  "Middle Franks": "中法蘭克王國",
  "Aquitaine": "亞奎丹公國",
  "Samanid Empire": "薩曼王朝",
  "Tahirid Sultanate": "塔希爾蘇丹國",
  "(Carolingian Empire)": "卡洛林帝國",
  "Norway-Denmark": "挪威-丹麥",
  "North Sea Empire": "北海帝國",
  "Eastern Kara-Khanids": "東喀喇汗國",
  "Western Karakhanid Khanate": "西喀喇汗國",
  "Almoravid Dynasty": "穆拉比特王朝",
  "Zengid dynasty": "贊吉王朝",
  "Almohad Caliphate": "穆瓦希德王朝",
  "Ghurid Dynasty": "古爾王朝",
  "Khwarezmid Empire": "花剌子模帝國",
  "Mamluk Dynasty": "馬穆魯克王朝",
  "Rasulid Dynasty": "拉蘇利王朝",
  "Marinid Sultanate": "馬林蘇丹國",
  "Holy Roman Empire Minor States": "神聖羅馬帝國諸邦",
  "Khalji Dynasty": "卡爾吉王朝",
  "Sukhothai Kingdom": "素可泰王國",
  "Tughlaq Dynasty": "圖格魯克王朝",
  "Kartids": "卡爾提德王朝",
  "Sarbadars": "薩爾巴達爾人",
  "Jalayirid Sultanate": "札剌亦兒蘇丹國",
  "Grand Duchy of Lithuania": "立陶宛大公國",
  "Muzaffarids": "穆扎法爾王朝",
  "White Horde": "白帳汗國",
  "Blue Horde": "藍帳汗國",
  "Northern Yuan": "北元",
  "(Polish-Lithuania Kingdom)": "波蘭-立陶宛王國",
  "Polish-Lithuanian Commonwealth": "波蘭-立陶宛聯邦",
  "Four Oirats": "四衛拉特",
  "Khanate of Sibir": "西伯利亞汗國",
  "House of Habsburg": "哈布斯堡王朝",
  "Nogai Horde": "諾蓋汗國",
  "House of Jagiellon": "雅蓋隆王朝",
  "House of Oldenburg": "奧爾登堡王朝",
  "Moghulistan": "蒙兀兒斯坦",
  "East Turkestan": "東突厥斯坦",
  "Mongol Khanate": "蒙古汗國",
  "Wattasid dynasty": "瓦塔斯王朝",
  "Kazakh Khanate": "哈薩克汗國",
  "Lodi Dynasty": "洛迪王朝",
  "Eastern Chagatai Khanate": "東察合台汗國",
  "Shaybanids": "沙班尼王朝",
  "(Portuguese Empire)": "葡萄牙帝國",
  "(Spanish Empire)": "西班牙帝國",
  "Khanate of Bukhara": "布哈拉汗國",
  "Eastern Moghulistan": "東蒙兀兒斯坦",
  "Shan States": "撣邦",
  "Tümed": "土默特",
  "Tsardom of Russia": "俄羅斯沙皇國",
  "Saadi Sultanate": "薩阿迪蘇丹國",
  "First Toungoo Empire": "第一東吁帝國",
  "Small Horde": "小帳汗國",
  "Dzungar Khanate": "準噶爾汗國",
  "Oirat Confederation": "衛拉特聯盟",
  "Li Zicheng": "李自成",
  "New Netherland": "新尼德蘭",
  "Southern Ming": "南明",
  "Commonwealth of England": "英格蘭聯邦",
  "Qasimids": "卡西米王朝",
  "(Dutch Republic)": "荷蘭共和國",
  "Pro-Swedish Poland": "親瑞典波蘭",
  "Nawabs of Bengal": "孟加拉納瓦布",
  "Hotaki Dynasty": "霍塔基王朝",
  "Afsharid Iran": "阿夫沙爾王朝",
  "Khanate of Khiva": "希瓦汗國",
  "Zand Dynasty": "桑德王朝",
  "Konbaung Dynasty": "貢榜王朝",
  "Thonburi Kingdom": "吞武里王國",
  "Rattanakosin Kingdom": "暹羅王國",
  "Emirate of Bukhara": "布哈拉酋長國",
  "Emirate of Diriyah": "德拉伊耶酋長國",
  "(French First Republic)": "法蘭西第一共和國",
  "French First Republic": "法蘭西第一共和國",
  "(French Directory)": "法國督政府",
  "French Directory": "法國督政府",
  "Sokoto Caliphate": "索科托哈里發國",
  "(First French Empire)": "法蘭西第一帝國",
  "First French Empire": "法蘭西第一帝國",
  "Austrian Empire": "奧地利帝國",
  "New Granada": "新格拉納達",
  "Muhammad Ali dynasty": "穆罕默德·阿里王朝",
  "Río de la Plata": "拉普拉塔",
  "Mexicans": "墨西哥",
  "Federal League": "聯邦聯盟",
  "Bourbon Kingdom of France": "波旁法蘭西王國",
  "(Bourbon Kingdom of France)": "波旁法蘭西王國",
  "United Kingdoms of Sweden and Norway": "瑞典-挪威聯合王國",
  "German Confederation": "德意志邦聯",
  "Burma": "緬甸",
  "British Cape Colony": "英屬開普殖民地",
  "First Mexican Empire": "墨西哥第一帝國",
  "Khanate of Kokand": "浩罕汗國",
  "Talpur Dynasty": "塔爾普爾王朝",
  "Merina Kingdom": "梅里納王國",
  "Federated Republic of Mexico": "墨西哥聯邦共和國",
  "Emirate of Nejd": "內志酋長國",
  "Emirate of Afghanistan": "阿富汗酋長國",
  "Nguyễn dynasty": "阮朝",
  "Sikh Empire": "錫克帝國",
  "Peru-Bolivian Confederation": "秘魯-玻利維亞聯邦",
  "Centralist Mexico": "墨西哥中央集權國",
  "Republic of Texas": "德克薩斯共和國",
  "Durrani Dynasty": "杜兰尼王朝",
  "Republic of the Rio Grande": "格蘭德河共和國",
  "Ottoman Tripolitania": "鄂圖曼的黎波里塔尼亞",
  "Emirate of Jabal Shammar": "賈巴爾沙馬爾酋長國",
  "(French Second Republic)": "法蘭西第二共和國",
  "French Second Republic": "法蘭西第二共和國",
  "(Second French Empire)": "法蘭西第二帝國",
  "Second French Empire": "法蘭西第二帝國",
  "Panthay Rebellion": "杜文秀起義",
  "British Raj": "英屬印度",
  "Granadine Confederation": "格拉納丁聯邦",
  "Taiping Heavenly Kingdom": "太平天國",
  "Second Mexican Empire": "墨西哥第二帝國",
  "Khedivate of Egypt": "埃及赫迪夫領",
  "Austria-Hungary": "奧匈帝國",
  "French Africa": "法屬非洲",
  "French Third Republic": "法蘭西第三共和國",
  "(French Third Republic)": "法蘭西第三共和國",
  "First Spanish Republic": "西班牙第一共和國",
  "British Africa": "英屬非洲",
  "German Africa": "德屬非洲",
  "Brazilian Republic": "巴西共和國",
  "Belgian Congo": "比屬剛果",
  "Mahdist State": "馬赫迪國",
  "South African Republic": "南非共和國",
  "Italian Africa": "義屬非洲",
  "Portuguese Republic": "葡萄牙共和國",
  "Great Mongol State": "大蒙古國",
  "Russian Republic": "俄羅斯共和國",
  "Kingdom of Hejaz": "漢志王國",
  "Kuomintang": "中國國民黨",
  "Ukrainian People's Republic": "烏克蘭人民共和國",
  "Weimar Republic": "威瑪共和國",
  "Second Polish Republic": "波蘭第二共和國",
  "Republics of the Soviet Union": "蘇維埃社會主義共和國聯邦",
  "Sultanate of Muscat and Oman": "馬斯喀特及阿曼蘇丹國",
  "Kingdom of Egypt": "埃及王國",
  "Provisional Priamurye Government": "濱海州臨時政府",
  "Pahlavi Dynasty": "巴列維王朝",
  "Kingdom of Afghanistan": "阿富汗王國",
  "Mongolian People's Republic": "蒙古人民共和國",
  "Kingdom of Hejaz and Nejd": "漢志內志王國",
  "Estado Novo": "新國家體制",
  "Anti-Kuomintang Coalition": "反國民黨聯盟",
  "Second Spanish Republic": "西班牙第二共和國",
  "Unitary State of Brazil": "巴西單一制國家",
  "Greenland": "格陵蘭",
  "Nazi Germany": "納粹德國",
  "Spanish Nationalists": "西班牙國民軍",
  "Francoist Spain": "法朗哥西班牙",
  "Free French": "自由法國",
  "(Vichy France)": "維琪法國",
  "Vichy France": "維琪法國",
  "French Fourth Republic": "法蘭西第四共和國",
  "(French Fourth Republic)": "法蘭西第四共和國",
  "Denmark": "丹麥",
  "Qatar Protectorate": "卡達保護國",
  "Republic of Egypt": "埃及共和國",
  "Kingdom of Libya": "利比亞王國",
  "United Arab Republic": "阿拉伯聯合共和國",
  "Arab Federation": "阿拉伯聯邦",
  "Iraqi Republic": "伊拉克共和國",
  "British East Africa": "英屬東非",
  "Federated Republic of Brazil": "巴西聯邦共和國",
  "Rhodesia": "羅德西亞",
  "People's Democratic Republic of Yemen": "南葉門人民民主共和國",
  "Republic of Afghanistan": "阿富汗共和國",
  "Zaire": "薩伊",
  "Zimbabwe Rhodesia": "辛巴威羅德西亞",
  "Mujahideen": "聖戰士",
  "Federated Republic of Germany": "德意志聯邦共和國",
  "Taliban": "塔利班",
  "State of Libya": "利比亞國",
  "Republic of Iraq": "伊拉克共和國",
  "Western Chu": "西楚",
  "Liao Dynasty": "遼朝",
  "Assyrian Egypt": "亞述埃及",
  "Twenty-sixth Dynasty of Egypt": "埃及第二十六王朝",
  "Thirtieth Dynasty of Egypt": "埃及第三十王朝",
  "Magadha - Haryanka dynasty": "摩揭陀-頻婆娑羅王朝",
  "Magadha - Shaishunaga dynasty": "摩揭陀-幼龍王朝",
  "Zhai": "翟",
  "Vakataka Kingdom": "伐卡塔卡王國",
  "Qocho Kingdom": "高昌回鶻王國",
  "(Taifas of Iberia)": "伊比利亞泰法",
  "Kenmu Restoration": "建武中興",
  "Safavid Dynasty": "薩法維王朝",
  "Iberian Union": "伊比利亞聯邦",
};

// Color overrides: match hardcoded data colors for consistency
const COLOR_OVERRIDE = {
  "Roman Republic": "#9333ea", "Roman Empire": "#dc2626",
  "Byzantine Empire": "#d97706", "Eastern Roman Empire": "#d97706",
  "Abbasid Caliphate": "#16a34a", "Umayyad Caliphate": "#16a34a",
  "Fatimid Caliphate": "#16a34a", "Ayyubid Sultanate": "#16a34a",
  "Mongol Empire": "#1d4ed8", "Golden Horde": "#1d4ed8",
  "Chagatai Khanate": "#1d4ed8", "Ilkhanate": "#1d4ed8",
  "Spanish Empire": "#eab308", "Kingdom of Spain": "#eab308",
  "British Empire": "#ec4899", "British Colonial Empire": "#ec4899",
  "Kingdom of Great Britain": "#ec4899",
  "(British Empire)": "#ec4899",
  "United States of America": "#ef4444",
  "Russian Empire": "#dc2626", "Russian Federation": "#dc2626",
  "(Russian Federation)": "#dc2626",
  "Union of Soviet Socialist Republics": "#dc2626",
  "Republics of the Soviet Union": "#dc2626",
  "Ottoman Empire": "#f59e0b",
  "Holy Roman Empire": "#8b5cf6", "(Holy Roman Empire)": "#8b5cf6",
  "French Fifth Republic": "#3b82f6", "(French Fifth Republic)": "#3b82f6",
  "French Consulate": "#3b82f6", "(French Consulate)": "#3b82f6",
  "Kingdom of France": "#3b82f6", "(Kingdom of France)": "#3b82f6",
  "Kingdom of Prussia": "#6b7280",
  "Habsburg Monarchy": "#a855f7", "(Habsburg Monarchy)": "#a855f7",
  "German Empire": "#6b7280",
  "Inca Empire": "#ec4899", "Aztec Empire": "#ec4899",
  "Mughal Empire": "#22c55e",
  "Safavid Empire": "#f59e0b", "Qajar Dynasty": "#f59e0b",
  "Parthian Empire": "#f59e0b", "Sasanian Empire": "#f59e0b",
  "Great Seljuk Empire": "#f59e0b", "Seljuk Dynasty": "#f59e0b",
  "Timurid Empire": "#f59e0b",
  "Mali Empire": "#a855f7", "Songhai Empire": "#a855f7",
  "Ghana Empire": "#a855f7",
  "Achaemenid Empire": "#f59e0b",
  "Swedish Empire": "#3b82f6",
  "Netherlands": "#f97316", "(Netherlands)": "#f97316",
  "Kingdom of Portugal": "#16a34a",
};

function assignColor(name) {
  // Check color override first
  if (COLOR_OVERRIDE[name]) return COLOR_OVERRIDE[name];

  // Region-based fallback with multiple color options per region
  const lower = name.toLowerCase();
  const REGION = {
    europe: ["roman","byzantin","frank","holy roman","spain","portugal","france","england",
      "britain","british","scotland","ireland","germany","prussia","austria","hungary","poland",
      "lithuania","russia","sweden","norway","denmark","dutch","netherlands","belgium","italy",
      "venice","genoa","papal","ottoman","serbia","bulgaria","croatia","bohemia","romania",
      "ukraine","finland","estonia","latvia","albania","greece"],
    middle_east: ["arab","abbasid","umayyad","fatimid","ayyubid","mamluk","assyria",
      "mesopotamia","levant","syria","israel","hejaz","saudi","yemen","iraq","turkish",
      "seljuq","rashidun","phoenicia","carthage","akkad","sumer","elam","urartu","babylon"],
    south_asia: ["india","maurya","gupta","mughal","delhi sultan","chola","pallava",
      "vijayanagara","maratha","persia","iran","safavid","qajar","parthia","sasanid",
      "kushan","gandhara","satavahana","bengal","deccan"],
    east_asia: ["korea","joseon","goryeo","silla","baekje","goguryeo","japan","yamato",
      "nara","heian","tokugawa","edo","meiji","taiwan","ryukyu"],
    southeast_asia: ["siam","thai","burma","burmese","khmer","angkor","champa","vietnam",
      "malacca","malay","srivijaya","majapahit","ayutthaya","sukhothai"],
    africa: ["egypt","kush","aksum","ethiopia","mali","songhai","ghana","zulu","kongo",
      "morocco","tunisia","algeria","libya","sudan","nubia"],
    americas: ["aztec","maya","inca","united state","american","canada","brazil","mexico",
      "argentina","chile","colombia","peru","venezuela","bolivia"],
    central_asia: ["turkic","uighur","karakhanid","ghaznavid","khwarazm","kazakh","uzbek",
      "turkmen","kyrgyz","tajik","bukhara","samarkand"],
    steppe: ["hunnic","xiongnu","scythian","mongol","tatar","kipchak","golden horde","chagatai"],
  };

  const REGION_COLORS = {
    europe: ["#3b82f6","#6366f1","#8b5cf6","#a78bfa","#818cf8"],
    middle_east: ["#f59e0b","#d97706","#b45309","#fbbf24","#f97316"],
    east_asia: ["#ef4444","#dc2626","#b91c1c","#f87171"],
    south_asia: ["#22c55e","#16a34a","#15803d","#4ade80"],
    southeast_asia: ["#06b6d4","#0891b2","#0e7490","#22d3ee"],
    africa: ["#a855f7","#9333ea","#7c3aed","#c084fc"],
    americas: ["#f97316","#ea580c","#c2410c","#fb923c","#06b6d4","#0891b2"],
    central_asia: ["#84cc16","#65a30d","#4d7c0f","#a3e635"],
    steppe: ["#78716c","#57534e","#44403c","#a8a29e"],
  };

  for (const [region, keywords] of Object.entries(REGION)) {
    for (const kw of keywords) {
      if (lower.includes(kw)) {
        const colors = REGION_COLORS[region] || ["#6b7280"];
        // Use name hash to pick a consistent but varied color from the region palette
        let hash = 0;
        for (let i = 0; i < name.length; i++) hash = ((hash << 5) - hash + name.charCodeAt(i)) | 0;
        return colors[Math.abs(hash) % colors.length];
      }
    }
  }
  return "#6b7280";
}

// Chinese dynasties to skip (hardcoded data is more detailed)
const CN_SHORT = /^(qin|song|teng|chen|cao|lu|zheng|cai|zhu|yan|wei|zhao|wu|qi|jin|han|chu|xu|hu|liao|dai|yue|hu|tang|lv|dong|xi|nan|bei|zhong)$/i;
const CN_REGEX = /china|chinese|han dynast|tang dynast|song dynast|yuan dynast|ming dynast|qing dynast|jin dynast|sui dynast|xia dynast|shang dynast|zhou dynast|qin dynast|tibet|nanzhao|dali|tufan|jurchen|khitan|tangut|manchu|spring and autumn|warring states|five dynasties|sixteen kingdoms|southern qi|northern qi|western jin|eastern jin|southern song|northern song|jiangnan|hou liang|hou tang|hou jin|hou han|hou zhou|ming xia|liang|wu zhang|western xia|great jin|kara khitai|uyghur|buyeo/i;

function roundCoords(coords) {
  // GeoJSON is [lng, lat] but Leaflet L.polygon() expects [lat, lng] — swap here
  return coords.map(c => [Math.round(c[1] * 10) / 10, Math.round(c[0] * 10) / 10]);
}

function simplify(coords, every) {
  if (coords.length <= 4) return coords;
  const r = [];
  for (let i = 0; i < coords.length; i += every) r.push(coords[i]);
  const last = coords[coords.length - 1];
  if (r[r.length - 1][0] !== last[0] || r[r.length - 1][1] !== last[1]) r.push(last);
  return r;
}

function process() {
  console.log('Loading GeoJSON...');
  const data = JSON.parse(fs.readFileSync(INPUT, 'utf-8'));
  console.log(`Total features: ${data.features.length}`);

  const polityMap = new Map();
  for (const feat of data.features) {
    const p = feat.properties || {};
    if (p.Type === 'RELATION') continue;
    const name = p.Name || '';
    const area = p.Area || 0;
    if (CN_SHORT.test(name) || CN_REGEX.test(name)) continue;
    if (area < 300000) continue;

    // Merge certain polities under a canonical name
    const MERGE_MAP = {
      "Republics of the Soviet Union": "Union of Soviet Socialist Republics",
      "Northern Yuan": "Yuan Dynasty",
    };
    const mergedName = MERGE_MAP[name] || name;

    // Skip colonial sub-entities that duplicate parent empires
    const SKIP_MERGE = /^(british africa|british east africa|british south africa|british west africa|french africa|french west africa|french equatorial africa|french east africa|italian africa|italian east africa|italian libya|italian somaliland|italian eritrea|german africa|german east africa|german south west africa|portuguese africa|portuguese east africa|portuguese west africa|belgian congo|spanish africa|spanish west africa|british india|british burma|british malaya|british north borneo|dutch east indies|french indochina|french guiana|french polynesia|new netherland|greenland|taiwan under japanese rule|korea under japanese rule)$/i;
    if (SKIP_MERGE.test(name)) continue;

    const existing = polityMap.get(mergedName);
    if (!existing) {
      polityMap.set(mergedName, { name: mergedName, area, fy: p.FromYear, ty: p.ToYear, geo: feat.geometry });
    } else {
      // Always merge time range; replace geometry only if larger
      existing.fy = Math.min(existing.fy, p.FromYear);
      existing.ty = Math.max(existing.ty, p.ToYear);
      if (area > existing.area) {
        existing.area = area;
        existing.geo = feat.geometry;
      }
    }
  }

  console.log(`Deduplicated to ${polityMap.size} polities`);

  const features = [];
  for (const polity of polityMap.values()) {
    const g = polity.geo || {};
    const zhName = ZH[polity.name] || polity.name;
    const color = assignColor(polity.name);
    const entry = { n: zhName, fy: polity.fy, ty: polity.ty, c: color };

    if (g.type === 'Polygon') {
      entry.g = (g.coordinates || []).map(r => roundCoords(simplify(r, 20)));
    } else if (g.type === 'MultiPolygon') {
      entry.gm = (g.coordinates || []).map(poly => poly.map(r => roundCoords(simplify(r, 20))));
    } else continue;

    features.push(entry);
  }

  console.log(`Features kept: ${features.length}`);

  const MIN_YEAR = -5000, MAX_YEAR = 2050;
  const yearIndex = new Array(MAX_YEAR - MIN_YEAR + 1).fill(null).map(() => []);
  for (let i = 0; i < features.length; i++) {
    const f = features[i];
    const start = Math.max(f.fy, MIN_YEAR);
    const end = Math.min(f.ty, MAX_YEAR);
    for (let y = start; y <= end; y++) {
      yearIndex[y - MIN_YEAR].push(i);
    }
  }

  fs.writeFileSync('cliopatria_features.js',
    'var CLIOPATRIA_FEATURES=' + JSON.stringify(features) + ';\n', 'utf-8');

  const indexData = [];
  for (let i = 0; i < yearIndex.length; i++) {
    if (yearIndex[i].length > 0) {
      indexData.push([i + MIN_YEAR, yearIndex[i]]);
    }
  }
  fs.writeFileSync('cliopatria_index.js',
    'var CLIOPATRIA_INDEX=' + JSON.stringify(indexData) + ';\n', 'utf-8');

  const fSize = fs.statSync('cliopatria_features.js').size;
  const iSize = fs.statSync('cliopatria_index.js').size;
  console.log(`Features: ${(fSize / 1024 / 1024).toFixed(1)} MB`);
  console.log(`Index: ${(iSize / 1024).toFixed(0)} KB`);
  console.log(`Total: ${((fSize + iSize) / 1024 / 1024).toFixed(1)} MB`);
}

process();
